# Generated by Django 5.0.1 on 2024-01-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='identifier',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
